export enum ReceiptType {
  FACTURA_A = "FACTURA_A",
  FACTURA_B = "FACTURA_B",
  FACTURA_C = "FACTURA_C",
  NOTA_CREDITO_A = "NOTA_CREDITO_A",
  NOTA_CREDITO_B = "NOTA_CREDITO_B",
  NOTA_CREDITO_C = "NOTA_CREDITO_C",
}
