export enum TaxCategory {
  RESPONSABLE_INSCRIPTO = "RESPONSABLE_INSCRIPTO",
  MONOTRIBUTO = "MONOTRIBUTO",
  EXENTO = "EXENTO",
  CONSUMIDOR_FINAL = "CONSUMIDOR_FINAL",
  SUJETO_NO_CATEGORIZADO = "SUJETO_NO_CATEGORIZADO",
  PROVEEDOR_DEL_EXTERIOR = "PROVEEDOR_DEL_EXTERIOR",
}
