spring:
  profiles:
    active: dev
  application:
    name: app
  jpa:
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expirationHours: 2

gemini:
  api:
    key: ${GEMINI_API_KEY}
