spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pymes?createDatabaseIfNotExist=true
    username: root
    password: chanochoca
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cookie:
  secure: false
  domain: localhost
  sameSite: Lax
