spring:
  profiles:
    active: dev
  application:
    name: app
  jpa:
    open-in-view: false

jwt:
  secret: 37kpH3ylTLuefkx6zECe0M3FLb8Gd+BFIUHXlhO4H0w= # Base64 256-bit
  expirationHours: 2

gemini:
  api:
    key: ${GEMINI_API_KEY}
